Repository XgridInc/xkops, pull requests merged in 2024-07, with the labels that each got.

#62 X workflow 2
  README.md
  xWorkflows/xWorkflow_2/data_flow_diagram.png
  xWorkflows/xWorkflow_2/docker-compose.yaml
  xWorkflows/xWorkflow_2/flask_backend/Dockerfile
  xWorkflows/xWorkflow_2/flask_backend/app.py
  xWorkflows/xWorkflow_2/flask_backend/requirements.txt
  xWorkflows/xWorkflow_2/k8s_yaml_files/flask-backend-deployment.yaml
  xWorkflows/xWorkflow_2/k8s_yaml_files/kubecost_query_pod.yaml
  xWorkflows/xWorkflow_2/k8s_yaml_files/mongodb-statefuleset.yaml
  xWorkflows/xWorkflow_2/kind_cluster/kind_cluster.yaml
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/Dockerfile
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/go.mod
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/go.sum
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/main.go
  xWorkflows/xWorkflow_2/readme.md
Labels: 2024, june

#61 Xworkflow 1 for XkOps
  xWorkflows/Xworkflow1/Readme.md
  xWorkflows/Xworkflow1/backend/Dockerfile
  xWorkflows/Xworkflow1/backend/app.py
  xWorkflows/Xworkflow1/backend/requirements.txt
  xWorkflows/Xworkflow1/go/kubecost-event/Dockerfile
  xWorkflows/Xworkflow1/go/kubecost-event/go.mod
  xWorkflows/Xworkflow1/go/kubecost-event/go.sum
  xWorkflows/Xworkflow1/go/kubecost-event/main.go
  xWorkflows/Xworkflow1/image.png
  xWorkflows/Xworkflow1/manifests/kubecostcronjob/cronjob.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/headless-service.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/statefulset.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/storageclass.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolume/unclaimed-volume1.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolume/unclaimed-volume2.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolumebackend/deployment.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolumebackend/service.yaml
  xWorkflows/Xworkflow1/rb-actions/my_playbook_repo/delete_persistent_volume.py
  xWorkflows/Xworkflow1/rb-actions/pyproject.toml
Labels: enhancement, 2024, june

#83 Added seperate namespace for each workflow in their manifests.
  xWorkflows/Xworkflow1/manifests/kubecostcronjob/cronjob.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/headless-service.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/statefulset.yaml
  xWorkflows/Xworkflow1/manifests/mongodb/storageclass.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolume/unclaimed-volume1.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolume/unclaimed-volume2.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolumebackend/deployment.yaml
  xWorkflows/Xworkflow1/manifests/unclaimedvolumebackend/service.yaml
  xWorkflows/xWorkflow_2/k8s_yaml_files/flask-backend-deployment.yaml
  xWorkflows/xWorkflow_2/k8s_yaml_files/kubecost_query_pod.yaml
  xWorkflows/xWorkflow_2/k8s_yaml_files/mongodb-statefuleset.yaml
Labels: enhancement, good first issue, 2024, july

#82 Improved Error handling in Xworkflow1 and Xworkflow2
  xWorkflows/Xworkflow1/backend/app.py
  xWorkflows/xWorkflow_2/flask_backend/app.py
Labels: enhancement, good first issue, 2024, backend, july

#84 Replaced error statements with logging in the kubecost query pods
  xWorkflows/Xworkflow1/go/kubecost-event/main.go
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/go.mod
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/go.sum
  xWorkflows/xWorkflow_2/kubecost_query_pod_go/main.go
Labels: enhancement, good first issue, 2024, july
